---
deployment:
  tasks:
    - current_path=`pwd` # set current path to variable
    - echo $pwd
    - if [ $current_path == "/home/technohe/repositories/public_sho" ]; then export DEPLOYPATH=/home/technohe/public_sho/; fi;
    - /bin/cp -r app $DEPLOYPATH
    - /bin/cp -r config $DEPLOYPATH
    - /bin/cp -r database $DEPLOYPATH
    - /bin/cp -r resources $DEPLOYPATH
    - /bin/cp -r routes $DEPLOYPATH
    - /bin/cp -r public $DEPLOYPATH
    - /bin/cp -r .htaccess $DEPLOYPATH
#    - /bin/cp -R package.json $DEPLOYPATH

